ads/urls.py
from django.urls import path
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('post-ads/', views.post_ads, name='post-ads'),
    path('post-ads/success', views.ads_success, name='ads_success'),
    path('ads-listing/', views.ads_listing, name='ads-listing'),
    path('ads/<int:pk>/', views.ads_detail, name='ads-detail'),
    path('ads/<int:pk>/delete/', views.ads_delete, name='ads-delete'),
    path('ads/<int:pk>/edit/', views.ads_edit, name='ads-edit'),
    path('category/<slug:slug>/', views.ads_category_archive, name='category-archive'),
    path('state/<slug:slug>/', views.ads_state_archive, name='state-archive'),
    path('city/<slug:slug>/', views.ads_city_archive, name='city-archive'),
    path('author/<int:pk>/', views.ads_author_archive, name='author-archive'),
    path('ads-search/', views.ads_search, name='ads-search'),
]

pracainzynierska/urls.py
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.template.defaulttags import url
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('authentication.urls')),
    path('', include('profiles.urls')),
    path('', include('ads.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

ads/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.urls import reverse
# Default User model
from django.contrib.auth.models import User
from django.dispatch import receiver  # add this
from django.db.models.signals import post_save  # add this
import csv


# Create your models here.

# Author Model
class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default="default-profile-pic.png", upload_to='uploads/profile-pictures', null=True)

    def __str__(self):
        return f'{self.user.username} Profiles'


# Ads Model
class Ads(models.Model):
    CONDITION = (
        ('Nowy', 'Nowy'),
        ('Używany', 'Używany'),
        ('Uszkodzony', 'Uszkodzony'),
    )

    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    description = RichTextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    date_created = models.DateTimeField(auto_now_add=True)
    state = models.ForeignKey('State', on_delete=models.CASCADE, null=True)
    city = models.ForeignKey('City', on_delete=models.CASCADE, null=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True)
    condition = models.CharField(max_length=100, choices=CONDITION)
    brand = models.CharField(max_length=200)
    phone = models.CharField(max_length=50)
    is_featured = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Ads"

    def __str__(self):
        return self.title


# State Model
class State(models.Model):
    state_name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, null=True)

    # overriding save method to add slug field from state name if not provided
    def save(self, *args, **kwargs):
        if not self.slug and self.state_name:
            self.slug = slugify(self.state_name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "States"

    def __str__(self):
        return self.state_name


# City Model
class City(models.Model):
    city_name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, null=True)

    # overriding save methodto add slug field from city name if not provided
    def save(self, *args, **kwargs):
        if not self.slug and self.city_name:
            self.slug = slugify(self.city_name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Cities"

    def __str__(self):
        return self.city_name


# Category Model
class Category(models.Model):
    category_name = models.CharField(max_length=100)
    category_image = models.ImageField(upload_to='uploads/category', blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)

    # overriding save method to add slug field from category name if not provided
    def save(self, *args, **kwargs):
        if not self.slug and self.category_name:
            self.slug = slugify(self.category_name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category_name


# Image Model
class AdsImages(models.Model):
    ads = models.ForeignKey(Ads, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d', default=None)

    def __str__(self):
        return self.ads.title

    class Meta:
        verbose_name_plural = 'Ads Images'

ads/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import *


class PostAdsForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control',
        'name': 'title',
        'placeholder': 'Title'
    }))

    description = forms.CharField(widget=CKEditorWidget(attrs={
        'type': 'text',
        'class': 'form-control',
        'name': 'description',
        'placeholder': 'Description'
    }))

    price = forms.CharField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'name': 'price',
        'placeholder': 'Price'
    }))

    city = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control',
        'name': 'city',
        'placeholder': 'City'
    }))

    brand = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control',
        'name': 'brand',
        'placeholder': 'Brand'
    }))

    phone = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control',
        'name': 'phone',
        'placeholder': 'Phone'
    }))

    class Meta:
        model = Ads
        fields = '__all__'
        exclude = ['author', 'date_created', 'is_featured']


class EditAdsForm(forms.ModelForm):
    title = forms.CharField(label="Tytuł", widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control',
        'name': 'title',
        'placeholder': 'Title'
    }))

    description = forms.CharField(widget=CKEditorWidget(attrs={
        'type': 'text',
        'class': 'form-control',
        'name': 'description',
        'placeholder': 'Description'
    }))

    price = forms.CharField(label="Cena", widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'name': 'price',
        'placeholder': 'Price'
    }))

    brand = forms.CharField(label="Marka", widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control',
        'name': 'brand',
        'placeholder': 'Brand'
    }))

    phone = forms.CharField(label="Telefon kontaktowy", widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control',
        'name': 'phone',
        'placeholder': 'Phone'
    }))

    class Meta:
        model = Ads
        fields = 'title', 'description', 'price', 'brand', 'phone'

ads/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.db.models import Count
from django.forms.models import model_to_dict
# Model Forms.
from .forms import PostAdsForm, EditAdsForm
from django.contrib.auth.forms import User
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.core.mail import send_mail

# importing messages
from django.contrib import messages


# from .ads.models import Author


# Create your views here.

# Post ads view
@login_required(login_url='login')
def post_ads(request):
    category_list = Category.objects.values_list('category_name', flat=True).distinct().order_by("category_name")
    condition_list = Ads.objects.values_list('condition', flat=True).distinct().order_by("condition")
    if request.method == 'POST':
        # Get ad title
        title = request.POST.get('title')

        # Get ad description
        description = request.POST.get('description')

        # Get ad category
        category = request.POST.get('category')
        # Check if the category exists
        category_check = Category.objects.filter(category_name=category).exists()
        if category_check:
            c = Category.objects.get(category_name=category)
        else:
            c = Category.objects.create(category_name=category)  # Create the category

        # Get ad price
        price = request.POST.get('price')

        # Get ad condition
        condition = request.POST.get('condition')

        # Get user's living state
        state = request.POST.get('state')

        # Check if the state exists
        state_check = State.objects.filter(state_name=state).exists()
        if state_check:
            s = State.objects.get(state_name=state)  # Get the state if exists
        else:
            s = State.objects.create(state_name=state)  # Create the state

        # Get user's living city
        city = request.POST.get('city')

        # Check if the city exists
        city_check = City.objects.filter(city_name=city).exists()
        if city_check:
            ci = City.objects.get(city_name=city)  # Get the city if exists
        else:
            ci = City.objects.create(city_name=city)  # Create the city

        # Get ad brand
        brand = request.POST.get('brand')

        # Get user's phone
        phone = request.POST.get('phone')

        # Get image files length
        length = request.POST.get('length')

        # Create the ad
        ads = Ads.objects.create(author=request.user.author, title=title, description=description, price=price,
                                 category=c, condition=condition, state=s, city=ci, brand=brand, phone=phone, )

        # Attach the images with the associated ad
        for file_num in range(0, int(length)):
            AdsImages.objects.create(
                ads=ads,
                image=request.FILES.get(f'images{file_num}')
            )

        # # Send email notificaton to Admin
        # mail_subject = "New Ads submitted"
        # sender_email = request.user.email
        # message = f"Dear Admin, you received a new ads request from {sender_email}"
        # print(message)
        # to_email = settings.EMAIL_HOST_USER
        # to_list = [to_email]
        # from_email = settings.EMAIL_HOST_USER

        # send_mail(
        #     mail_subject,
        #     message,
        #     from_email,
        #     to_list,
        #     fail_silently=False,
        # )

    context = {
        'category_list': category_list,
        'condition_list': condition_list,
    }

    return render(request, 'ads/post-ads.html', context)


# Ads listing view
def ads_listing(request):
    ads_listing = Ads.objects.all()
    category_listing = Category.objects.annotate(total_ads=Count('ads')).order_by('category_name')

    context = {
        'ads_listing': ads_listing,
        'category_listing': category_listing
    }

    return render(request, 'ads/ads-listing.html', context)


# Ads detail view
def ads_detail(request, pk):
    ads_detail = get_object_or_404(Ads, pk=pk)
    ads_photos = AdsImages.objects.filter(ads=ads_detail)

    context = {
        'ads_detail': ads_detail,
        'ads_photos': ads_photos,
    }

    return render(request, 'ads/ads-detail.html', context)


# Ads category archive view
def ads_category_archive(request, slug):
    category = get_object_or_404(Category, slug=slug)
    ads_by_category = Ads.objects.filter(category=category)

    context = {
        'category': category,
        'ads_by_category': ads_by_category
    }

    return render(request, 'ads/category-archive.html', context)


# Ads state archive view
def ads_state_archive(request, slug):
    state = get_object_or_404(State, slug=slug)
    ads_by_state = Ads.objects.filter(state=state)

    context = {
        'state': state,
        'ads_by_state': ads_by_state
    }

    return render(request, 'ads/state-archive.html', context)


# Ads city archive view
def ads_city_archive(request, slug):
    city = get_object_or_404(City, slug=slug)
    ads_by_city = Ads.objects.filter(city=city)

    context = {
        'city': city,
        'ads_by_city': ads_by_city
    }

    return render(request, 'ads/city-archive.html', context)


# Ads author archive view
def ads_author_archive(request, pk):
    author = get_object_or_404(Author, pk=pk)
    ads_by_author = Ads.objects.filter(author=author)

    context = {
        'author': author,
        'ads_by_author': ads_by_author
    }

    return render(request, 'ads/author-archive.html', context)


# Ads search/filter view
def ads_search(request):
    state = request.GET.get('state_name')
    category = request.GET.get('category_name')
    title = request.GET.get('title_name')
    # if title:
    #     ads_search_result = Ads.objects.filter(title__contains=title)
    # elif state:
    #     ads_search_result = Ads.objects.filter(state__state_name=state)
    # elif category:
    #     ads_search_result = Ads.objects.filter(category__category_name=category)
    # else:
    if state == "":
        ads_search_result = Ads.objects.filter(title__contains=title)
    else:
        ads_search_result = Ads.objects.filter(title__contains=title).filter(state__state_name=state)

    context = {
        'ads_search_result': ads_search_result,
    }

    return render(request, 'ads/ads-search.html', context)


# Ads delete view
@login_required(login_url='login')
def ads_delete(request, pk):
    ad = get_object_or_404(Ads, pk=pk)
    ad.delete()
    return redirect("dashboard")


@login_required(login_url='login')
def ads_edit(request, pk):
    instance = Ads.objects.get(id=pk)
    if request.method == 'POST':

        edit_form = EditAdsForm(request.POST, instance=instance)
        if edit_form.is_valid():
            edit_form.save()
            messages.success(request, f"Zaktualizowano pomyslnie")
            return redirect('profile-ads')
    else:
        edit_form = EditAdsForm(instance=instance)

    context = {
        'edit_form': edit_form,
    }
    return render(request, 'ads/ads-edit.html', context)


def ads_success(request):
    return render(request, 'post-ads/ads_success.html')

ads/templates/ads/ads-listing.html
{% extends "base.html" %}
{% block content %}

<!-- Page Header Start -->
<div class="page-header" style="background: url(assets/img/banner1.jpg);">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumb-wrapper">
          <div style="margin-bottom:20px;"></div>
          <h2 class="product-title">Wszystkie ogłoszenia</h2>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Page Header End -->

<!-- Main container Start -->
<div class="main-container section-padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-12 col-xs-12 page-sidebar">
        <aside>
          <div class="widget categories">
            <h4 class="widget-title">Wszystkie kategorie</h4>
            <ul class="nav flex-column">
                              {% for category in category_listing %}
              <li class="nav-item">
                <a href="{% url 'category-archive' category.slug %}">
                  <i class="lni-folder"></i>
                  {{ category }} <span class="category-counter">({{ category.total_ads }})</span>
                </a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </aside>
      </div>
      <div class="col-lg-8 col-md-12 col-xs-12 page-content">
        <div class="adds-wrapper">

          <div class="tab-content">
            <div id="list-view" class="tab-pane fade active show">
              <div class="row">
                {% for ad_listing in ads_listing %}
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  <div class="featured-box">
                    <figure>

                      <a href="{% url 'ads-detail' ad_listing.id %}">
                        {% for img in ad_listing.adsimages_set.all %}
                        {% if forloop.first %}
                        <img class="img-fluid" src="{{ img.image.url }}" alt="">
                        {% endif %}
                        {% endfor %}

                      </a>
                    </figure>
                    <div class="feature-content">
                      <div class="product">
                        <a href="{% url 'category-archive' ad_listing.category.slug %}"><i class="lni-folder"></i> {{ ad_listing.category }}</a>
                      </div>
                      <h4><a href="{% url 'ads-detail' ad_listing.id %}">{{ ad_listing.title }}</a></h4>
                      <span>Dodane: {{ ad_listing.date_created }}</span>
                      <ul class="address">
                        <li>
                          <i class="lni-map-marker"></i> {{ ad_listing.city }}, {{ ad_listing.state }}
                        </li>
                        <li>
                          <i class="lni-alarm-clock"></i> {{ ad_listing.date_created|date }}
                        </li>
                        <li>
                          <i class="lni-user"></i> {{ ad_listing.author.user }}
                        </li>
                        <li>
                          <i class="lni-package"></i> {{ ad_listing.condition }}
                        </li>
                      </ul>
                      <div class="listing-bottom">
                        <h3 class="price float-left">{{ ad_listing.price }} zł</h3>

                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Main container End -->

{% endblock content %}

ads/templates/ads/ads-search.html
{% extends "base.html" %}
{% block content %}

<!-- Latest Ads Listing Section Start -->
<section class="featured section-padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div style="margin-bottom:20px;"></div>
          <h3 class="section-title">Wyniki wyszukiwania:</h3>
        <div style="margin-bottom:20px;"></div>
        </div>
      {% if ads_search_result %}
        {% for ad_search in ads_search_result %}

        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
          <div class="featured-box">
            <figure>
              <a href="{% url 'ads-detail' ad_search.id %}">
                  {% for img in ad_search.adsimages_set.all %}
                  {% if forloop.first %}
                      <img class="img-fluid" src="{{ img.image.url }}" alt="">
                  {% endif %}
                  {% endfor %}
              </a>
            </figure>

            <div class="feature-content">
              <div class="product">
                  <a href="{% url 'category-archive' ad_search.category.slug %}"><i class="lni-folder"></i>{{ ad_search.category.category_name }}</a>

              </div>
              <h4><a href="{% url 'ads-detail' ad_search.id %}">{{ ad_search.title }}</a></h4>
              <span>Dodano: {{ ad_search.date_created }}</span>
              <ul class="address">
                <li>
                  <i class="lni-map-marker"></i>{{ ad_search.state }}
                </li>
                <li>
                  <i class="lni-alarm-clock"></i>{{ ad_search.date_created | date }}
                </li>
                <li>
                  <i class="lni-user"></i> {{ ad_search.author.user }}
                </li>
                <li>
                  <i class="lni-package"></i>{{ ad_search.condition }}
                </li>
              </ul>
              <div class="listing-bottom">
                <h3 class="price float-left"> {{ ad_search.price }} zł</h3>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <div class="container">
          <div class="col-lg-12">
            <h4 class="text-center">Nie znaleziono ogłoszeń</h4>
          </div>
        </div>
      {% endif %}

    </div>
  </div>
</section>
<!-- Latest Ads Listing Section End -->


{% endblock content %}

ads/templates/ads/author-archive.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="{{ request.user.author.profile_pic.url }}" alt="avatar"
              class="rounded img-fluid" style="width: 150px;">
            <h5 class="my-3">{{author.user}}</h5>
            <p><i class="lni-calendar"></i> Dołączył  {{ author.user.date_joined }}</p>
          </div>
        </div>

      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Imię i nazwisko</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{author.user.first_name}} {{author.user.last_name}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Adres e-mail</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{author.user.email}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="card mb-4">
          <div class="card-body">
              <h5>Ogłoszenia dodane przez {{ author.user }} </h5>
<div class="row">
      {% if ads_by_author %}
      {% for ads in ads_by_author %}
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
          <div class="featured-box">

            <figure>
              <a href="{% url 'ads-detail' ads.id %}">
                  {% for img in ads.adsimages_set.all %}
                  {% if forloop.first %}
                      <img class="img-fluid" src="{{ img.image.url }}" alt="">
                  {% endif %}
                  {% endfor %}
              </a>
            </figure>

            <div class="feature-content">
              <h4><a href="{% url 'ads-detail' ads.id %}">{{ ads.title}}</a></h4>
              <span>Dodano: {{ ads.date_created}}</span>
              <ul class="address">
                <li>
                  <i class="lni-map-marker"></i>{{ ads.state}}
                </li>
                <li>
                  <i class="lni-alarm-clock"></i>{{ ads.date_created | date}}
                </li>
                <li>
                  <i class="lni-user"></i>{{ ads.author.user }}
                </li>
                <li>
                  <i class="lni-package"></i>{{ ads.condition }}
                </li>
              </ul>
              <div class="listing-bottom">
                <h3 class="price float-left">{{ ads.price }} zł</h3>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      {% else %}
        <div class="container">
          <div class="col-lg-12">
            <h4 class="text-center">Nie znaleziono ogłoszeń tego użytkownika</h4>
          </div>
        </div>
      {% endif %}
    </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>


{% endblock content %}

ads/templates/ads/category-archive.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Category Archive Section Start -->
<section class="featured section-padding">
  <div class="container">
    <!--  ogloszenia w wojewodztwie-->
    <div class="py-5 text-center">
        <div class="container-fluid">
            <h3 class="alert alert-light">Ogłoszenia z kategorii: {{category.category_name}}</h3> <br>
          <div class="row hidden-md-up">
            {% if ads_by_category %}
              {% for ads in ads_by_category %}
              <div class="col-md-3" style="padding-bottom: 5px;">
                  <div class="card" style="border: none;">
                    <div class="card-block">
                        {% for img in ads.adsimages_set.all %}
                            {% if forloop.first %}
                            <a href="{% url 'ads-detail' ads.id %}"><img class="img-responsive rounded mx-auto d-block" style="max-height:200px" src="{{ img.image.url }}" alt=""></a>
                            {% endif %}
                        {% endfor %}

                        <div class="container ">
                        <h5 class="card-title text-truncate">{{ads.title }}</h5>
                        <p><i class="lni-user"></i> Ogloszenie dodał: {{ ads.author.user }}</p>
                        <p><i class="lni-map-marker"></i> {{ ads.city }}, {{ ads.state }}</p>
                      <p>Ogłoszenie dodano: {{ ads.date_created }}</p>
                        <h4>Cena: {{ ads.price }} zł</h4>
                            </div>
                    </div>
                  </div>
             </div>
              {% endfor %}
            {% else %}
            <div class="container">
              <div class="col-lg-12">
                <h4 class="text-center">Nie znaleziono ogłoszeń z tej kategorii</h4>
              </div>
          </div>
            {% endif %}

          </div>
        </div>
    </div>
    </div>
  </div>
</section>
<!-- Category Archive Section End -->


{% endblock content %}

ads/templates/ads/city-archive.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Category Archive Section Start -->
<section class="featured section-padding">
  <div class="container">
    <!--  ogloszenia w wojewodztwie-->
    <div class="py-5 text-center">
        <div class="container-fluid">
            <h3 class="alert alert-light">Ogłoszenia w mieście: {{city.city_name}}</h3> <br>
          <div class="row hidden-md-up">
            {% if ads_by_city %}
              {% for ads in ads_by_city %}
              <div class="col-md-3" style="padding-bottom: 5px;">
                  <div class="card" style="border: none;">
                    <div class="card-block">
                        {% for img in ads.adsimages_set.all %}
                            {% if forloop.first %}
                            <a href="{% url 'ads-detail' ads.id %}"><img class="img-responsive rounded mx-auto d-block" style="max-height:200px" src="{{ img.image.url }}" alt=""></a>
                            {% endif %}
                        {% endfor %}

                        <div class="container ">
                        <h5 class="card-title text-truncate">{{ads.title }}</h5>
                        <p><i class="lni-user"></i> Ogloszenie dodał: {{ ads.author.user }}</p>
                        <p><i class="lni-map-marker"></i> {{ ads.city }}, {{ ads.state }}</p>
                      <p>Ogłoszenie dodano: {{ ads.date_created }}</p>
                        <h4>Cena: {{ ads.price }} zł</h4>
                            </div>
                    </div>
                  </div>
             </div>
              {% endfor %}
            {% else %}
            <div class="container">
              <div class="col-lg-12">
                <h4 class="text-center">Nie znaleziono ogłoszeń w tym mieście</h4>
              </div>
          </div>
            {% endif %}

          </div>
        </div>
    </div>
    </div>
  </div>
</section>
<!-- Category Archive Section End -->


{% endblock content %}

ads/templates/ads/state-archive.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- State Archive Section Start -->
<section class="featured section-padding">
  <div style="margin-top:20px;"></div>
  <div class="container">

<!--  ogloszenia w wojewodztwie-->
    <div class="py-5 text-center">
        <div class="container-fluid">
            <h3 class="alert alert-light">Ogłoszenia w województwie: {{state.state_name}}</h3> <br>
          <div class="row hidden-md-up">
            {% if ads_by_state %}
              {% for ads in ads_by_state %}
              <div class="col-md-3" style="padding-bottom: 5px;">
                  <div class="card" style="border: none;">
                    <div class="card-block">
                        {% for img in ads.adsimages_set.all %}
                            {% if forloop.first %}
                            <a href="{% url 'ads-detail' ads.id %}"><img class="img-responsive rounded mx-auto d-block" style="max-height:200px" src="{{ img.image.url }}" alt=""></a>
                            {% endif %}
                        {% endfor %}

                        <div class="container ">
                        <h5 class="card-title text-truncate">{{ads.title }}</h5>
                        <p><i class="lni-user"></i> Ogloszenie dodał: {{ ads.author.user }}</p>
                        <p><i class="lni-map-marker"></i> {{ ads.city }}, {{ ads.state }}</p>
                      <p>Ogłoszenie dodano: {{ ads.date_created }}</p>
                        <h4>Cena: {{ ads.price }} zł</h4>
                            </div>
                    </div>
                  </div>
             </div>
              {% endfor %}
            {% else %}
            <div class="container">
              <div class="col-lg-12">
                <h4 class="text-center">Nie znaleziono ogłoszeń w tym województwie</h4>
              </div>
          </div>
            {% endif %}

          </div>
        </div>
    </div>

<!-- ogloszenia w wojewodztwie - koniec -->

{% endblock content %}